Layout/AlignArguments:
  EnforcedStyle: with_fixed_indentation

Metrics/LineLength:
  Enabled: false

Naming/MethodParameterName:
  MinNameLength: 1

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma
