[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
itertools = "0.10.5"
path-absolutize = "3.0.14"
regex = "1.7.0"
serde = { version = "1.0.149", features = ["derive"] }
